/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package storemgt;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
/**
 *
 * @author asenl
 */
public class calc extends javax.swing.JFrame {

    /**
     * Creates new form calc
     */
    public calc() {
        initComponents();
        CalcScreen.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                e.consume(); // Consume the event to prevent typing
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        CalcScreen = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Num0 = new javax.swing.JButton();
        NumPoint = new javax.swing.JButton();
        Num4 = new javax.swing.JButton();
        Multiplication = new javax.swing.JButton();
        Subtraction = new javax.swing.JButton();
        Num1 = new javax.swing.JButton();
        Equals = new javax.swing.JButton();
        Num2 = new javax.swing.JButton();
        Num6 = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Num7 = new javax.swing.JButton();
        Divission = new javax.swing.JButton();
        Num8 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        Num9 = new javax.swing.JButton();
        Addition = new javax.swing.JButton();
        Num5 = new javax.swing.JButton();
        Num3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Calc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        Num0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Num0.setText("0");
        Num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num0ActionPerformed(evt);
            }
        });

        NumPoint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NumPoint.setText(".");
        NumPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumPointActionPerformed(evt);
            }
        });

        Num4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Num4.setText("4");
        Num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num4ActionPerformed(evt);
            }
        });

        Multiplication.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Multiplication.setText("*");
        Multiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicationActionPerformed(evt);
            }
        });

        Subtraction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Subtraction.setText("-");
        Subtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtractionActionPerformed(evt);
            }
        });

        Num1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Num1.setText("1");
        Num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num1ActionPerformed(evt);
            }
        });

        Equals.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Equals.setText("=");
        Equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualsActionPerformed(evt);
            }
        });

        Num2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Num2.setText("2");
        Num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num2ActionPerformed(evt);
            }
        });

        Num6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Num6.setText("6");
        Num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num6ActionPerformed(evt);
            }
        });

        Clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Clear.setText("AC");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Num7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Num7.setText("7");
        Num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num7ActionPerformed(evt);
            }
        });

        Divission.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Divission.setText("/");
        Divission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivissionActionPerformed(evt);
            }
        });

        Num8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Num8.setText("8");
        Num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num8ActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delete.setText("X");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        Num9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Num9.setText("9");
        Num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num9ActionPerformed(evt);
            }
        });

        Addition.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Addition.setText("+");
        Addition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdditionActionPerformed(evt);
            }
        });

        Num5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Num5.setText("5");
        Num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num5ActionPerformed(evt);
            }
        });

        Num3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Num3.setText("3");
        Num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("<-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Num0)
                        .addGap(18, 18, 18)
                        .addComponent(NumPoint)
                        .addGap(18, 18, 18)
                        .addComponent(delete)
                        .addGap(18, 18, 18)
                        .addComponent(Equals))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Num1)
                        .addGap(18, 18, 18)
                        .addComponent(Num2)
                        .addGap(18, 18, 18)
                        .addComponent(Num3)
                        .addGap(18, 18, 18)
                        .addComponent(Addition))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Num4)
                        .addGap(18, 18, 18)
                        .addComponent(Num5)
                        .addGap(18, 18, 18)
                        .addComponent(Num6)
                        .addGap(18, 18, 18)
                        .addComponent(Subtraction))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Num7)
                        .addGap(18, 18, 18)
                        .addComponent(Num8)
                        .addGap(18, 18, 18)
                        .addComponent(Num9)
                        .addGap(18, 18, 18)
                        .addComponent(Multiplication))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Divission)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clear)
                    .addComponent(Divission)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num7)
                    .addComponent(Num8)
                    .addComponent(Num9)
                    .addComponent(Multiplication))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num4)
                    .addComponent(Num5)
                    .addComponent(Num6)
                    .addComponent(Subtraction))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num1)
                    .addComponent(Num2)
                    .addComponent(Num3)
                    .addComponent(Addition))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num0)
                    .addComponent(NumPoint)
                    .addComponent(delete)
                    .addComponent(Equals))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(CalcScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CalcScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private class printNum{
        static int indexOfopp = -1;
        static char opp;
        static float answer;
        
        static String showNum(String onScreen_,String num){
            String show = onScreen_+num;
            return show;
        }
        
        static boolean printOpp(String onScreen_){
            char [] input = onScreen_.toCharArray();
            
            boolean addopp = true;
            for(int i=0; i<input.length; i++){
                if(input[i] == '+' || input[i]=='*' || input[i]=='/'){
                    addopp = false;
                }
            }
            return addopp;
        }
        
        static boolean opps(String onScreen_, char opp){
            int there = 0;
            boolean printOpp = false;
            char [] input = onScreen_.toCharArray();
            for(int i=0; i<input.length; i++){
                if(input[i] == opp){
                    there+=1;
                }
            }
            if(opp != '-'){
                if(input.length == 0){
                    //System.out.println("cant put '+' ");
                } else if(input[input.length-1] == opp){
                    //System.out.println("cant put '+' ");
                } else{
                    if(there == 0){
                        //CalcScreen.setText(printNum.showNum(CalcScreen.getText(),"+"));
                        printOpp = true;
                    }else{
                        printOpp = false;
                    }
                }
            } else{
                for(int i=0; i<input.length; i++){
                    if(input[i] == '*' || input[i] == '+' || input[i] == '/'){
                        there+=1;
                    }
                }
                if(input.length == 0){
                    printOpp = true;
                } else if(input[input.length-1] == '-'){
                    printOpp = false;
                } else if(input[input.length-1] == '+' || input[input.length-1] == '/' || input[input.length-1] == '*'){
                    printOpp = true;
                } else{
                    if(input.length >= 1){
                        if(input[0] != '-'){
                            if(there < 1){
                                printOpp=false;
                            }
                            there+=1;
                        }
                    }
                    if(there < 2){
                        printOpp = true;
                    }else{
                        printOpp=false;
                    }
                }
            }
            System.out.println(there);
            return printOpp;
        }
        
        
        static float calc(String text){
            StringBuilder right = new StringBuilder();
            StringBuilder left = new StringBuilder();
            char [] input = text.toCharArray();
            indexOfopp = -1;
            for(int i=0; i<input.length; i++){
                //System.out.println("length: " + input.length);
                if(input[i] == '+' || input[i] == '/' || input[i] == '*'  ){
                    indexOfopp = i;
                    opp = input[i];
                    break;
                } else if (input[i] == '-'){
                    if(i>0){
                        indexOfopp = i;
                        opp = input[i];
                    }                                       
                }
            }
            //get the right hand value
            for(int i=0; i<indexOfopp; i++){
                right.append(input[i]);
            }
            //get the left hand value
            for(int i=(indexOfopp+1); i<input.length; i++){
                left.append(input[i]);
            }
            for(int i = 0; i<input.length; i++){
                System.out.println("input: "+input[i]);
            }
            switch (opp) {
                case '+':
                    answer = Float.parseFloat(String.valueOf(right)) + Float.parseFloat(String.valueOf(left));
                    break;
                case '-':
                    answer = Float.parseFloat(String.valueOf(right)) - Float.parseFloat(String.valueOf(left));
                    break;
                case '*':
                    answer = Float.parseFloat(String.valueOf(right)) * Float.parseFloat(String.valueOf(left));
                    break;
                case '/':
                    answer = Float.parseFloat(String.valueOf(right)) / Float.parseFloat(String.valueOf(left));
                    break;
                default:
                    break;
            }
            return answer;
            
            /*System.out.println("left"+ left);
            System.out.println("right"+ right);
            System.out.println("oop index: "+indexOfopp);*/
        }
    }
    
    private void Num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num0ActionPerformed
        // TODO add your handling code here:
        CalcScreen.setText(printNum.showNum(CalcScreen.getText(),"0"));
    }//GEN-LAST:event_Num0ActionPerformed

    private void Num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num1ActionPerformed
        // TODO add your handling code here:
        CalcScreen.setText(printNum.showNum(CalcScreen.getText(),"1"));
    }//GEN-LAST:event_Num1ActionPerformed

    private void Num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num2ActionPerformed
        // TODO add your handling code here:
        CalcScreen.setText(printNum.showNum(CalcScreen.getText(),"2"));
    }//GEN-LAST:event_Num2ActionPerformed

    private void Num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num3ActionPerformed
        // TODO add your handling code here:
        CalcScreen.setText(printNum.showNum(CalcScreen.getText(),"3"));
    }//GEN-LAST:event_Num3ActionPerformed

    private void Num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num4ActionPerformed
        // TODO add your handling code here:
        CalcScreen.setText(printNum.showNum(CalcScreen.getText(),"4"));
    }//GEN-LAST:event_Num4ActionPerformed

    private void Num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num5ActionPerformed
        // TODO add your handling code here:
        CalcScreen.setText(printNum.showNum(CalcScreen.getText(),"5"));
    }//GEN-LAST:event_Num5ActionPerformed

    private void Num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num6ActionPerformed
        // TODO add your handling code here:
        CalcScreen.setText(printNum.showNum(CalcScreen.getText(),"6"));
    }//GEN-LAST:event_Num6ActionPerformed

    private void Num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num7ActionPerformed
        // TODO add your handling code here:
        CalcScreen.setText(printNum.showNum(CalcScreen.getText(),"7"));
    }//GEN-LAST:event_Num7ActionPerformed

    private void Num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num8ActionPerformed
        // TODO add your handling code here:
        CalcScreen.setText(printNum.showNum(CalcScreen.getText(),"8"));
    }//GEN-LAST:event_Num8ActionPerformed

    private void Num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num9ActionPerformed
        // TODO add your handling code here:
        CalcScreen.setText(printNum.showNum(CalcScreen.getText(),"9"));
    }//GEN-LAST:event_Num9ActionPerformed

    private void NumPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumPointActionPerformed
        // TODO add your handling code here:
        CalcScreen.setText(printNum.showNum(CalcScreen.getText(),"."));
    }//GEN-LAST:event_NumPointActionPerformed

    private void AdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdditionActionPerformed
        // TODO add your handling code here:    
        if(printNum.printOpp(CalcScreen.getText())){
            if(printNum.opps(CalcScreen.getText(), '+')){
                CalcScreen.setText(printNum.showNum(CalcScreen.getText(),"+"));
            }
        }
    }//GEN-LAST:event_AdditionActionPerformed

    private void SubtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtractionActionPerformed
        // TODO add your handling code here:
        
        if(printNum.opps(CalcScreen.getText(), '-')){
            CalcScreen.setText(printNum.showNum(CalcScreen.getText(),"-"));
        }
    }//GEN-LAST:event_SubtractionActionPerformed

    private void MultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicationActionPerformed
        // TODO add your handling code here:
        if(printNum.printOpp(CalcScreen.getText())){
            if(printNum.opps(CalcScreen.getText(), '*')){
                CalcScreen.setText(printNum.showNum(CalcScreen.getText(),"*"));
            }
        }
    }//GEN-LAST:event_MultiplicationActionPerformed

    private void DivissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivissionActionPerformed
        // TODO add your handling code here:
        if(printNum.printOpp(CalcScreen.getText())){
            if(printNum.opps(CalcScreen.getText(), '/')){
                CalcScreen.setText(printNum.showNum(CalcScreen.getText(),"/"));
            }
        } 
    }//GEN-LAST:event_DivissionActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        CalcScreen.setText("");
        
    }//GEN-LAST:event_ClearActionPerformed

    private void EqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualsActionPerformed
        // TODO add your handling code here:
        String calText = CalcScreen.getText();
        CalcScreen.setText(String.valueOf(printNum.calc(calText)));        
        
    }//GEN-LAST:event_EqualsActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        StringBuilder onScreen = new StringBuilder();
        char [] input = CalcScreen.getText().toCharArray();
        for(int i=0; i<input.length-1; i++){
                onScreen.append(input[i]);
        }
        CalcScreen.setText(String.valueOf(onScreen));
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ScreenManager.goBack();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calc().setVisible(true);
                               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addition;
    private javax.swing.JTextField CalcScreen;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Divission;
    private javax.swing.JButton Equals;
    private javax.swing.JButton Multiplication;
    private javax.swing.JButton Num0;
    private javax.swing.JButton Num1;
    private javax.swing.JButton Num2;
    private javax.swing.JButton Num3;
    private javax.swing.JButton Num4;
    private javax.swing.JButton Num5;
    private javax.swing.JButton Num6;
    private javax.swing.JButton Num7;
    private javax.swing.JButton Num8;
    private javax.swing.JButton Num9;
    private javax.swing.JButton NumPoint;
    private javax.swing.JButton Subtraction;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
